services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: skygraph-frontend:latest
    container_name: skygraph-frontend
    restart: unless-stopped
    ports:
      - '3000:80'
    networks:
      - skygraph-network

networks:
  skygraph-network:
    name: skygraph-network
    driver: bridge
